package com.ecoshop.shipping.service.service;

import com.ecoshop.common.exception.BusinessException;
import com.ecoshop.shipping.service.courier.Courier;
import com.ecoshop.shipping.service.courier.Courier.BookingRequest;
import com.ecoshop.shipping.service.courier.Courier.BookingResult;
import com.ecoshop.shipping.service.courier.Courier.RateQuote;
import com.ecoshop.shipping.service.domain.Shipment;
import com.ecoshop.shipping.service.domain.ShipmentStatus;
import com.ecoshop.shipping.service.domain.TrackingEvent;
import com.ecoshop.shipping.service.dto.ShippingDtos.*;
import com.ecoshop.shipping.service.repo.ShipmentRepository;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class ShippingService {

    private static final Logger log = LoggerFactory.getLogger(ShippingService.class);
    public static final String TOPIC_SHIPMENT_CREATED = "shipment.created";
    public static final String TOPIC_SHIPMENT_STATUS_CHANGED = "shipment.status.changed";
    private static final String DEFAULT_FROM_PINCODE = "560001"; // Bengaluru DC

    private final ShipmentRepository shipmentRepository;
    private final Courier courier;
    private final KafkaTemplate<String, Object> kafkaTemplate;

    @Transactional(readOnly = true)
    public RateQuoteResponse quoteRate(RateQuoteRequest req) {
        RateQuote q = courier.getRate(req.fromPincode(), req.toPincode(), req.weightGrams());
        return new RateQuoteResponse(courier.name(), q.cost(), q.estimatedDelivery(), q.transitDays());
    }

    @Transactional
    public ShipmentResponse createShipment(CreateShipmentRequest req) {
        // Idempotency: one shipment per order
        return shipmentRepository.findByOrderId(req.orderId())
                .map(this::toResponse)
                .orElseGet(() -> doCreate(req));
    }

    private ShipmentResponse doCreate(CreateShipmentRequest req) {
        AddressDto addr = req.destination();
        String fromPin = req.fromPincode() != null ? req.fromPincode() : DEFAULT_FROM_PINCODE;

        BookingResult booking = courier.book(new BookingRequest(
                req.orderId().toString(),
                fromPin,
                addr.postalCode(),
                req.weightGrams(),
                addr.recipientName(),
                addr.phone(),
                req.codAmount()
        ));

        Shipment shipment = Shipment.builder()
                .orderId(req.orderId())
                .userId(req.userId())
                .courier(courier.name())
                .trackingNumber(booking.trackingNumber())
                .labelUrl(booking.labelUrl())
                .status(ShipmentStatus.LABEL_GENERATED)
                .shippingCost(booking.cost())
                .weightGrams(req.weightGrams())
                .estimatedDelivery(booking.estimatedDelivery())
                .toRecipientName(addr.recipientName())
                .toPhone(addr.phone())
                .toLine1(addr.line1())
                .toLine2(addr.line2())
                .toCity(addr.city())
                .toState(addr.state())
                .toPostalCode(addr.postalCode())
                .toCountry(addr.country() != null ? addr.country() : "IN")
                .build();

        shipment.addEvent(TrackingEvent.builder()
                .status(ShipmentStatus.CREATED)
                .occurredAt(Instant.now())
                .description("Shipment created")
                .build());
        shipment.addEvent(TrackingEvent.builder()
                .status(ShipmentStatus.LABEL_GENERATED)
                .occurredAt(Instant.now())
                .description("Label generated by " + courier.name())
                .build());

        shipment = shipmentRepository.save(shipment);
        log.info("Shipment {} booked for order {}: tracking={} cost={}",
                shipment.getId(), req.orderId(), booking.trackingNumber(), booking.cost());

        publishCreated(shipment);
        return toResponse(shipment);
    }

    @Transactional(readOnly = true)
    public ShipmentResponse getByOrderId(UUID orderId) {
        Shipment s = shipmentRepository.findByOrderId(orderId)
                .orElseThrow(() -> BusinessException.notFound("SHIPMENT_NOT_FOUND",
                        "No shipment for order " + orderId));
        return toResponse(s);
    }

    @Transactional(readOnly = true)
    public ShipmentResponse getByTrackingNumber(String tracking) {
        Shipment s = shipmentRepository.findByTrackingNumber(tracking)
                .orElseThrow(() -> BusinessException.notFound("SHIPMENT_NOT_FOUND",
                        "No shipment with tracking " + tracking));
        return toResponse(s);
    }

    /**
     * Update shipment status. Called by webhook from courier in production, or by admin/cron.
     * Adds a tracking event and publishes status-change Kafka event.
     */
    @Transactional
    public ShipmentResponse updateStatus(UUID shipmentId, UpdateStatusRequest req) {
        Shipment s = shipmentRepository.findById(shipmentId)
                .orElseThrow(() -> BusinessException.notFound("SHIPMENT_NOT_FOUND",
                        "Shipment " + shipmentId + " not found"));
        ShipmentStatus from = s.getStatus();
        if (from == req.status()) return toResponse(s);

        s.setStatus(req.status());
        if (req.status() == ShipmentStatus.DELIVERED) {
            s.setDeliveredAt(Instant.now());
        }
        s.addEvent(TrackingEvent.builder()
                .status(req.status())
                .occurredAt(Instant.now())
                .location(req.location())
                .description(req.description())
                .build());

        log.info("Shipment {} status: {} -> {}", s.getId(), from, req.status());
        publishStatusChanged(s, from);
        return toResponse(s);
    }

    @Transactional
    public ShipmentResponse cancel(UUID shipmentId) {
        Shipment s = shipmentRepository.findById(shipmentId)
                .orElseThrow(() -> BusinessException.notFound("SHIPMENT_NOT_FOUND",
                        "Shipment " + shipmentId + " not found"));
        if (s.getStatus() == ShipmentStatus.DELIVERED || s.getStatus() == ShipmentStatus.IN_TRANSIT
            || s.getStatus() == ShipmentStatus.OUT_FOR_DELIVERY) {
            throw BusinessException.badRequest("CANNOT_CANCEL",
                    "Cannot cancel a shipment in status " + s.getStatus());
        }
        try {
            courier.cancel(s.getTrackingNumber());
        } catch (Exception e) {
            log.warn("Courier cancellation failed (continuing anyway): {}", e.getMessage());
        }
        ShipmentStatus from = s.getStatus();
        s.setStatus(ShipmentStatus.CANCELLED);
        s.addEvent(TrackingEvent.builder()
                .status(ShipmentStatus.CANCELLED)
                .occurredAt(Instant.now())
                .description("Cancelled")
                .build());
        publishStatusChanged(s, from);
        return toResponse(s);
    }

    private void publishCreated(Shipment s) {
        Map<String, Object> evt = new HashMap<>();
        evt.put("eventId", UUID.randomUUID().toString());
        evt.put("shipmentId", s.getId().toString());
        evt.put("orderId", s.getOrderId().toString());
        evt.put("trackingNumber", s.getTrackingNumber());
        evt.put("courier", s.getCourier());
        evt.put("estimatedDelivery", s.getEstimatedDelivery() != null ? s.getEstimatedDelivery().toString() : null);
        kafkaTemplate.send(TOPIC_SHIPMENT_CREATED, s.getOrderId().toString(), evt);
    }

    private void publishStatusChanged(Shipment s, ShipmentStatus from) {
        Map<String, Object> evt = new HashMap<>();
        evt.put("eventId", UUID.randomUUID().toString());
        evt.put("shipmentId", s.getId().toString());
        evt.put("orderId", s.getOrderId().toString());
        evt.put("trackingNumber", s.getTrackingNumber());
        evt.put("fromStatus", from.name());
        evt.put("toStatus", s.getStatus().name());
        kafkaTemplate.send(TOPIC_SHIPMENT_STATUS_CHANGED, s.getOrderId().toString(), evt);
    }

    public ShipmentResponse toResponse(Shipment s) {
        AddressDto addr = new AddressDto(
                s.getToRecipientName(), s.getToPhone(), s.getToLine1(), s.getToLine2(),
                s.getToCity(), s.getToState(), s.getToPostalCode(), s.getToCountry()
        );
        List<TrackingEventResponse> events = s.getTrackingEvents().stream()
                .map(e -> new TrackingEventResponse(e.getStatus(), e.getOccurredAt(), e.getLocation(), e.getDescription()))
                .toList();
        return new ShipmentResponse(
                s.getId(), s.getOrderId(), s.getUserId(),
                s.getCourier(), s.getTrackingNumber(), s.getLabelUrl(),
                s.getStatus(), s.getShippingCost(), s.getWeightGrams(),
                s.getEstimatedDelivery(), s.getDeliveredAt(), addr, events
        );
    }
}
